include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for VnStat
LUCI_DEPENDS:=+luci-base +luci-compat +vnstat +vnstati
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
